export const SET_COMPANY_INFO = "SET_COMPANY_INFO";
export const SET_EMPLOYEES_DATA = "SET_EMPLOYEES_DATA";
export const SET_EMPLOYEE_DETAILS = "SET_EMPLOYEE_DETAILS";
export const SET_PAGE_NO = "SET_PAGE_NO";
export const SET_MAX_RECORDS = "SET_MAX_RECORDS";
export const SET_TOTAL_RECORDS = "SET_TOTAL_RECORDS";
